---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  environment:
    PDR_USER:
      from_secret: docker-user-local
    PDR_PASS:
      from_secret: docker-pass-local
  commands:
  - docker build -t pdr.nephatrine.net/nephatrine/gitea-runner:cached --target builder .
  - docker build -t pdr.nephatrine.net/nephatrine/gitea-runner:latest .
  - docker login -p "$PDR_PASS" -u "$PDR_USER" pdr.nephatrine.net
  - docker push pdr.nephatrine.net/nephatrine/gitea-runner:latest
  - docker logout pdr.nephatrine.net
- name: publish
  environment:
    DOCKER_USER:
      from_secret: docker-user
    DOCKER_PASS:
      from_secret: docker-pass
  commands:
  - docker tag pdr.nephatrine.net/nephatrine/gitea-runner:latest nephatrine/gitea-runner:latest
  - docker tag pdr.nephatrine.net/nephatrine/gitea-runner:latest nephatrine/gitea-runner:0.1.2
  - docker tag pdr.nephatrine.net/nephatrine/gitea-runner:latest nephatrine/gitea-runner:0.1
  - docker tag pdr.nephatrine.net/nephatrine/gitea-runner:latest nephatrine/gitea-runner:0
  - docker login -p "$DOCKER_PASS" -u "$DOCKER_USER"
  - docker push -a nephatrine/gitea-runner
  - docker logout
  depends_on:
  - build

---
kind: pipeline
name: notify

steps:
- name: notify-status
  image: appleboy/drone-discord
  failure: ignore
  settings:
    avatar_url: https://code.nephatrine.net/assets/img/logo.png
    message: "build of **[{{repo.name}}:{{commit.branch}}](<https://code.nephatrine.net/NephNET/{{repo.name}}/src/branch/{{commit.branch}}>)** returned [{{build.status}}](<{{build.link}}>)."
    username: DroneCI
    webhook_id:
      from_secret: infra-notify-id
    webhook_token:
      from_secret: infra-notify-token

depends_on:
- default

trigger:
  status:
  - success
  - failure

---
kind: signature
hmac: 8d21c50d6456bfea7b9605894f3dc4f6128b48eef92c705a93a3ddab8aca064f

...
