# SPDX-FileCopyrightText: 2023-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: CC0-1.0

services:
  gitea-runner:
    build: .
    container_name: gitea-runner
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      GITEA_INSTANCE_URL: https://gitea.example.net
      GITEA_RUNNER_REGISTRATION_TOKEN:
      GITEA_RUNNER_NAME: test
    volumes:
      - /mnt/containers/gitea-runner:/mnt/config
      - /var/run/docker.sock:/run/docker.sock
