services:
  act_runner:
    build: .
    container_name: act_runner
    environment:
      TZ: America/New_York
      PUID: 1000
      PGID: 1000
      GITEA_INSTANCE_URL: http://localhost:3000/
      GITEA_RUNNER_REGISTRATION_TOKEN: 
      GITEA_RUNNER_NAME: test
      GITEA_RUNNER_LABELS: test
    volumes:
      - /mnt/containers/act_runner:/mnt/config
      - /var/run/docker.sock:/run/docker.sock
